// SPDX-License-Identifier: AGPL-3.0-or-later
//! UI-owned temporary write authorization and retry bookkeeping.
//!
//! This module has no protocol, UI, mutex, or wall-clock dependency. The caller
//! supplies identities from the current document and an already authenticated
//! client. Only trusted UI actions may call `trusted_grant`/`trusted_renew`.
//! A queued request must be claimed before `begin` is called. `Begin::New` is
//! only a decision, never an authorization permit: preflight, commit checks,
//! editing and `finish` must remain within the same UI callback. Finish the real
//! result before rendering/publishing, including failures and unchanged edits.

use std::collections::{HashMap, VecDeque};
use std::time::{Duration, Instant};

pub(crate) const LEASE_DURATION: Duration = Duration::from_secs(5 * 60);
const RESULT_TTL: Duration = Duration::from_secs(24 * 60 * 60);
const RESULT_LIMIT: usize = 1024;

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub(crate) struct Scope {
    pub instance: String,
    pub project: String,
    pub session: String,
}

/// Internal identity only; this does not define a wire operationId format.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct OperationKey {
    pub client: String,
    pub document_session: String,
    pub client_sequence: u64,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum RegistryError {
    ScopeMismatch,
    Unauthorized,
    LeaseExpired,
    ClientConflict,
    AlreadyGranted,
    InvalidInput,
    InvalidSequence,
    ParameterMismatch,
    OutcomeUnknown,
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) enum LeaseStatus<'a> {
    Unauthorized,
    Active {
        scope: &'a Scope,
        client: &'a str,
        remaining_minutes: u64,
    },
    Expired {
        scope: &'a Scope,
        client: &'a str,
    },
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) enum Begin<R> {
    New,
    Cached(R),
}

struct Lease {
    scope: Scope,
    client: String,
    token: String,
    expires_at: Instant,
}

enum Outcome<R> {
    InProgress,
    Completed(R),
}

struct Record<P, R> {
    sequence: u64,
    params: P,
    recorded_at: Instant,
    outcome: Outcome<R>,
}

struct History<P, R> {
    highest_sequence: u64,
    records: VecDeque<Record<P, R>>,
}

impl<P, R> History<P, R> {
    fn prune(&mut self, now: Instant) {
        self.records
            .retain(|record| now.saturating_duration_since(record.recorded_at) < RESULT_TTL);
        while self.records.len() > RESULT_LIMIT {
            self.records.pop_front();
        }
    }
}

/// One registry belongs to the current Canvas document held by the UI.
/// Binding a new instance/project/session invalidates authorization immediately.
/// Histories include the full scope to isolate even accidentally reused sessions.
/// Unreachable histories are discarded when binding changes; only the current
/// session's highest sequences survive result eviction. Restoring an old Scope
/// never restores its grant or results (document-session IDs must be unique).
pub(crate) struct WriteRegistry<P, R> {
    scope: Option<Scope>,
    lease: Option<Lease>,
    histories: HashMap<(String, Scope), History<P, R>>,
}

impl<P: PartialEq + Clone, R: Clone> Default for WriteRegistry<P, R> {
    fn default() -> Self {
        Self::new()
    }
}

impl<P: PartialEq + Clone, R: Clone> WriteRegistry<P, R> {
    pub fn new() -> Self {
        Self {
            scope: None,
            lease: None,
            histories: HashMap::new(),
        }
    }

    /// Call with the UI's actual binding, including None after close. This never
    /// grants or extends a lease. An unchanged binding keeps its exact deadline.
    pub fn bind_scope(&mut self, scope: Option<Scope>) {
        if self.scope != scope {
            self.lease = None;
            self.histories.clear();
            self.scope = scope;
        }
    }

    fn check_scope(&self, current: &Scope, claimed: &Scope) -> Result<(), RegistryError> {
        if self.scope.as_ref() != Some(current) || current != claimed {
            return Err(RegistryError::ScopeMismatch);
        }
        Ok(())
    }

    /// The token must be freshly generated by the trusted caller. Existing
    /// active authorization for this client is extended only by explicit renew.
    pub fn trusted_grant(
        &mut self,
        scope: &Scope,
        client: &str,
        token: String,
        now: Instant,
    ) -> Result<(), RegistryError> {
        self.check_scope(scope, scope)?;
        if client.is_empty() || token.is_empty() {
            return Err(RegistryError::InvalidInput);
        }
        if let Some(lease) = &self.lease
            && now < lease.expires_at
        {
            return Err(if lease.client == client {
                RegistryError::AlreadyGranted
            } else {
                RegistryError::ClientConflict
            });
        }
        let expires_at = now
            .checked_add(LEASE_DURATION)
            .ok_or(RegistryError::InvalidInput)?;
        self.lease = Some(Lease {
            scope: scope.clone(),
            client: client.to_owned(),
            token,
            expires_at,
        });
        Ok(())
    }

    /// A distinct, explicit trusted UI action may renew an active or expired
    /// lease for its original client. Revocation/binding changes require grant.
    pub fn trusted_renew(
        &mut self,
        scope: &Scope,
        client: &str,
        token: String,
        now: Instant,
    ) -> Result<(), RegistryError> {
        self.check_scope(scope, scope)?;
        if client.is_empty() || token.is_empty() {
            return Err(RegistryError::InvalidInput);
        }
        let lease = self.lease.as_mut().ok_or(RegistryError::Unauthorized)?;
        if lease.client != client {
            return Err(if now < lease.expires_at {
                RegistryError::ClientConflict
            } else {
                RegistryError::Unauthorized
            });
        }
        let expires_at = now
            .checked_add(LEASE_DURATION)
            .ok_or(RegistryError::InvalidInput)?;
        lease.token = token;
        lease.expires_at = expires_at;
        Ok(())
    }

    pub fn revoke(&mut self) {
        self.lease = None;
    }

    /// Suitable for a UI refresh on user actions or expiration; minutes are
    /// rounded up so the UI does not need a per-second countdown.
    pub fn lease_status(&self, now: Instant) -> LeaseStatus<'_> {
        let Some(lease) = &self.lease else {
            return LeaseStatus::Unauthorized;
        };
        if now >= lease.expires_at {
            return LeaseStatus::Expired {
                scope: &lease.scope,
                client: &lease.client,
            };
        }
        let remaining = lease.expires_at.duration_since(now);
        let whole_minutes = remaining.as_secs() / 60;
        let fraction = remaining.as_secs() % 60 != 0 || remaining.subsec_nanos() != 0;
        LeaseStatus::Active {
            scope: &lease.scope,
            client: &lease.client,
            remaining_minutes: whole_minutes + u64::from(fraction),
        }
    }

    /// Must also be called immediately before an actual commit, together with
    /// the caller's owner, revision, selection and object checks.
    pub fn authorize(
        &self,
        current: &Scope,
        claimed: &Scope,
        authenticated_client: &str,
        token: &str,
        now: Instant,
    ) -> Result<(), RegistryError> {
        self.check_scope(current, claimed)?;
        let lease = self.lease.as_ref().ok_or(RegistryError::Unauthorized)?;
        if lease.scope != *current || lease.client != authenticated_client || lease.token != token {
            return Err(RegistryError::Unauthorized);
        }
        if now >= lease.expires_at {
            return Err(RegistryError::LeaseExpired);
        }
        Ok(())
    }

    /// Authentication and current identities precede all cache access. The
    /// caller must only check fresh revisions/selection on the New branch.
    /// Reserving a sequence immediately makes duplicate/panic retries unknown.
    pub fn begin(
        &mut self,
        current: &Scope,
        claimed: &Scope,
        key: &OperationKey,
        token: &str,
        params: &P,
        now: Instant,
    ) -> Result<Begin<R>, RegistryError> {
        self.authorize(current, claimed, &key.client, token, now)?;
        if key.document_session != claimed.session {
            return Err(RegistryError::ScopeMismatch);
        }
        if key.client_sequence == 0 {
            return Err(RegistryError::InvalidSequence);
        }
        let history = self
            .histories
            .entry((key.client.clone(), claimed.clone()))
            .or_insert_with(|| History {
                highest_sequence: 0,
                records: VecDeque::new(),
            });
        history.prune(now);
        if let Some(record) = history
            .records
            .iter()
            .find(|record| record.sequence == key.client_sequence)
        {
            if record.params != *params {
                return Err(RegistryError::ParameterMismatch);
            }
            return match &record.outcome {
                Outcome::Completed(result) => Ok(Begin::Cached(result.clone())),
                Outcome::InProgress => Err(RegistryError::OutcomeUnknown),
            };
        }
        if key.client_sequence <= history.highest_sequence {
            return Err(RegistryError::OutcomeUnknown);
        }
        history.highest_sequence = key.client_sequence;
        history.records.push_back(Record {
            sequence: key.client_sequence,
            params: params.clone(),
            recorded_at: now,
            outcome: Outcome::InProgress,
        });
        history.prune(now);
        Ok(Begin::New)
    }

    /// Stores only the result; the params captured by begin cannot be replaced.
    /// This deliberately does not reauthorize an already committed edit: a real
    /// result must survive expiry/revocation between commit and result storage.
    /// Never call this from another callback or for an operation not begun here.
    pub fn finish(
        &mut self,
        scope: &Scope,
        key: &OperationKey,
        result: R,
        now: Instant,
    ) -> Result<(), RegistryError> {
        if key.document_session != scope.session {
            return Err(RegistryError::ScopeMismatch);
        }
        let history = self
            .histories
            .get_mut(&(key.client.clone(), scope.clone()))
            .ok_or(RegistryError::OutcomeUnknown)?;
        let record = history
            .records
            .iter_mut()
            .find(|record| record.sequence == key.client_sequence)
            .ok_or(RegistryError::OutcomeUnknown)?;
        if !matches!(record.outcome, Outcome::InProgress) {
            return Err(RegistryError::OutcomeUnknown);
        }
        record.outcome = Outcome::Completed(result);
        record.recorded_at = now;
        history.prune(now);
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Clone, Debug, PartialEq, Eq)]
    struct Params {
        revision: u64,
        selection_revision: u64,
        dx: i32,
    }

    type Registry = WriteRegistry<Params, &'static str>;

    fn scope() -> Scope {
        Scope {
            instance: "instance".into(),
            project: "project".into(),
            session: "session".into(),
        }
    }

    fn params() -> Params {
        Params {
            revision: 4,
            selection_revision: 2,
            dx: 3,
        }
    }

    fn key(sequence: u64) -> OperationKey {
        OperationKey {
            client: "alice".into(),
            document_session: "session".into(),
            client_sequence: sequence,
        }
    }

    fn granted(now: Instant) -> Registry {
        let mut registry = Registry::new();
        registry.bind_scope(Some(scope()));
        registry
            .trusted_grant(&scope(), "alice", "token".into(), now)
            .unwrap();
        registry
    }

    fn begin(
        registry: &mut Registry,
        sequence: u64,
        now: Instant,
    ) -> Result<Begin<&'static str>, RegistryError> {
        registry.begin(&scope(), &scope(), &key(sequence), "token", &params(), now)
    }

    #[test]
    fn default_denies_and_minutes_ceil_until_exact_expiry() {
        let now = Instant::now();
        let mut registry = Registry::new();
        assert_eq!(registry.lease_status(now), LeaseStatus::Unauthorized);
        registry.bind_scope(Some(scope()));
        assert_eq!(
            begin(&mut registry, 1, now),
            Err(RegistryError::Unauthorized)
        );
        let registry = granted(now);
        for (elapsed, minutes) in [(0, 5), (1, 5), (60, 4), (299, 1)] {
            assert_eq!(
                registry.lease_status(now + Duration::from_secs(elapsed)),
                LeaseStatus::Active {
                    scope: &scope(),
                    client: "alice",
                    remaining_minutes: minutes,
                }
            );
        }
        assert_eq!(
            registry.lease_status(now + Duration::from_secs(240) - Duration::from_nanos(1)),
            LeaseStatus::Active {
                scope: &scope(),
                client: "alice",
                remaining_minutes: 2,
            }
        );
        assert!(matches!(
            registry.lease_status(now + LEASE_DURATION),
            LeaseStatus::Expired { .. }
        ));
        assert_eq!(
            registry.authorize(&scope(), &scope(), "alice", "token", now + LEASE_DURATION),
            Err(RegistryError::LeaseExpired)
        );
    }

    #[test]
    fn explicit_renew_rotates_token_and_revoke_requires_new_grant() {
        let now = Instant::now();
        let mut registry = granted(now);
        assert_eq!(
            registry.trusted_grant(&scope(), "alice", "x".into(), now),
            Err(RegistryError::AlreadyGranted)
        );
        let renewed = now + Duration::from_secs(280);
        registry
            .trusted_renew(&scope(), "alice", "new".into(), renewed)
            .unwrap();
        assert_eq!(
            registry.authorize(&scope(), &scope(), "alice", "token", renewed),
            Err(RegistryError::Unauthorized)
        );
        assert_eq!(
            registry.authorize(&scope(), &scope(), "alice", "new", now + LEASE_DURATION),
            Ok(())
        );
        assert_eq!(
            registry.authorize(&scope(), &scope(), "alice", "new", renewed + LEASE_DURATION),
            Err(RegistryError::LeaseExpired)
        );
        registry
            .trusted_renew(&scope(), "alice", "again".into(), renewed + LEASE_DURATION)
            .unwrap();
        registry.revoke();
        assert_eq!(
            registry.trusted_renew(&scope(), "alice", "x".into(), now),
            Err(RegistryError::Unauthorized)
        );
        assert_eq!(
            begin(&mut registry, 100, now),
            Err(RegistryError::Unauthorized)
        );
    }

    #[test]
    fn another_client_cannot_take_active_lease() {
        let now = Instant::now();
        let mut registry = granted(now);
        assert_eq!(
            registry.trusted_grant(&scope(), "bob", "b".into(), now),
            Err(RegistryError::ClientConflict)
        );
        assert_eq!(
            registry.trusted_renew(&scope(), "bob", "b".into(), now),
            Err(RegistryError::ClientConflict)
        );
        registry
            .trusted_grant(&scope(), "bob", "b".into(), now + LEASE_DURATION)
            .unwrap();
        assert_eq!(
            registry.authorize(&scope(), &scope(), "alice", "token", now + LEASE_DURATION),
            Err(RegistryError::Unauthorized)
        );
    }

    #[test]
    fn binding_identity_changes_revoke_without_implicit_extension() {
        let now = Instant::now();
        let mut registry = granted(now);
        registry.bind_scope(Some(scope()));
        assert_eq!(
            begin(&mut registry, 1, now + LEASE_DURATION),
            Err(RegistryError::LeaseExpired)
        );
        for field in 0..3 {
            let mut registry = granted(now);
            let mut next = scope();
            match field {
                0 => next.instance = "next".into(),
                1 => next.project = "next".into(),
                _ => next.session = "next".into(),
            }
            assert_eq!(
                registry.authorize(&next, &scope(), "alice", "token", now),
                Err(RegistryError::ScopeMismatch)
            );
            registry.bind_scope(Some(next.clone()));
            assert_eq!(
                registry.authorize(&next, &scope(), "alice", "token", now),
                Err(RegistryError::ScopeMismatch)
            );
            assert_eq!(
                registry.authorize(&next, &next, "alice", "token", now),
                Err(RegistryError::Unauthorized)
            );
            registry
                .trusted_grant(&next, "alice", "new".into(), now)
                .unwrap();
            assert_eq!(
                registry.authorize(&next, &scope(), "alice", "new", now),
                Err(RegistryError::ScopeMismatch)
            );
        }
        registry.bind_scope(None);
        assert_eq!(registry.lease_status(now), LeaseStatus::Unauthorized);
    }

    #[test]
    fn binding_changes_discard_unreachable_sessions_without_restoring_grants() {
        let now = Instant::now();
        let mut registry = granted(now);
        assert_eq!(begin(&mut registry, 1, now), Ok(Begin::New));
        registry.finish(&scope(), &key(1), "old", now).unwrap();
        for seq in 0..100 {
            let mut next = scope();
            next.session = format!("session-{seq}");
            registry.bind_scope(Some(next.clone()));
            assert!(registry.histories.is_empty());
            registry
                .trusted_grant(&next, "alice", "token".into(), now)
                .unwrap();
            let mut next_key = key(1);
            next_key.document_session = next.session.clone();
            assert_eq!(
                registry.begin(&next, &next, &next_key, "token", &params(), now),
                Ok(Begin::New)
            );
            assert_eq!(registry.histories.len(), 1);
        }
        registry.bind_scope(Some(scope()));
        assert_eq!(
            begin(&mut registry, 1, now),
            Err(RegistryError::Unauthorized)
        );
        assert!(registry.histories.is_empty());
    }

    #[test]
    fn retry_authentication_precedes_cache_and_sequence() {
        let now = Instant::now();
        let mut registry = granted(now);
        assert_eq!(begin(&mut registry, 1, now), Ok(Begin::New));
        registry.finish(&scope(), &key(1), "moved", now).unwrap();
        for change_instance in [true, false] {
            let mut old_claim = scope();
            if change_instance {
                old_claim.instance = "old-instance".into();
            } else {
                old_claim.session = "old-session".into();
            }
            assert_eq!(
                registry.begin(&scope(), &old_claim, &key(1), "token", &params(), now),
                Err(RegistryError::ScopeMismatch)
            );
        }
        assert_eq!(
            registry.begin(&scope(), &scope(), &key(1), "wrong", &params(), now),
            Err(RegistryError::Unauthorized)
        );
        assert_eq!(
            begin(&mut registry, 1, now + LEASE_DURATION),
            Err(RegistryError::LeaseExpired)
        );
        assert_eq!(
            begin(&mut registry, 100, now + LEASE_DURATION),
            Err(RegistryError::LeaseExpired)
        );
        registry.revoke();
        assert_eq!(
            begin(&mut registry, 1, now),
            Err(RegistryError::Unauthorized)
        );
        assert_eq!(
            begin(&mut registry, 100, now),
            Err(RegistryError::Unauthorized)
        );
    }

    #[test]
    fn successful_retry_keeps_original_versions_and_rejects_changed_params() {
        let now = Instant::now();
        let mut registry = granted(now);
        assert_eq!(begin(&mut registry, 1, now), Ok(Begin::New));
        registry
            .finish(&scope(), &key(1), "revision 5", now)
            .unwrap();
        // The caller checks current revision only for New; original expected 4
        // must return its original revision-5 result after the edit succeeds.
        assert_eq!(
            begin(&mut registry, 1, now),
            Ok(Begin::Cached("revision 5"))
        );
        let mut changed = params();
        changed.revision = 5;
        assert_eq!(
            registry.begin(&scope(), &scope(), &key(1), "token", &changed, now),
            Err(RegistryError::ParameterMismatch)
        );
        changed = params();
        changed.dx += 1;
        assert_eq!(
            registry.begin(&scope(), &scope(), &key(1), "token", &changed, now),
            Err(RegistryError::ParameterMismatch)
        );
        assert_eq!(
            registry.finish(&scope(), &key(1), "overwrite", now),
            Err(RegistryError::OutcomeUnknown)
        );
        assert_eq!(
            begin(&mut registry, 1, now),
            Ok(Begin::Cached("revision 5"))
        );
    }

    #[test]
    fn eviction_and_expiration_keep_highest_sequence() {
        let now = Instant::now();
        let mut registry = granted(now);
        for seq in 1..=1025 {
            assert_eq!(begin(&mut registry, seq, now), Ok(Begin::New));
            registry.finish(&scope(), &key(seq), "done", now).unwrap();
        }
        assert_eq!(
            registry.histories.values().next().unwrap().records.len(),
            RESULT_LIMIT
        );
        assert_eq!(
            begin(&mut registry, 1, now),
            Err(RegistryError::OutcomeUnknown)
        );
        assert_eq!(begin(&mut registry, 2, now), Ok(Begin::Cached("done")));
        let expired = now + RESULT_TTL;
        registry
            .trusted_renew(&scope(), "alice", "token".into(), expired)
            .unwrap();
        assert_eq!(
            begin(&mut registry, 1025, expired),
            Err(RegistryError::OutcomeUnknown)
        );
        assert_eq!(
            begin(&mut registry, 1024, expired),
            Err(RegistryError::OutcomeUnknown)
        );
        assert_eq!(begin(&mut registry, 1026, expired), Ok(Begin::New));
    }

    #[test]
    fn in_progress_and_abandoned_entries_never_reexecute() {
        let now = Instant::now();
        let mut registry = granted(now);
        assert_eq!(begin(&mut registry, 7, now), Ok(Begin::New));
        assert_eq!(
            begin(&mut registry, 7, now),
            Err(RegistryError::OutcomeUnknown)
        );
        let mut changed = params();
        changed.selection_revision += 1;
        assert_eq!(
            registry.begin(&scope(), &scope(), &key(7), "token", &changed, now),
            Err(RegistryError::ParameterMismatch)
        );
        assert_eq!(
            begin(&mut registry, 6, now),
            Err(RegistryError::OutcomeUnknown)
        );
        let expired = now + RESULT_TTL;
        registry
            .trusted_renew(&scope(), "alice", "token".into(), expired)
            .unwrap();
        assert_eq!(
            begin(&mut registry, 7, expired),
            Err(RegistryError::OutcomeUnknown)
        );
    }

    #[test]
    fn invalid_sequence_and_client_session_isolation() {
        let now = Instant::now();
        let mut registry = granted(now);
        assert_eq!(
            begin(&mut registry, 0, now),
            Err(RegistryError::InvalidSequence)
        );
        let mut wrong = key(1);
        wrong.document_session = "wrong".into();
        assert_eq!(
            registry.begin(&scope(), &scope(), &wrong, "token", &params(), now),
            Err(RegistryError::ScopeMismatch)
        );
        assert!(registry.histories.is_empty());
        assert_eq!(begin(&mut registry, u64::MAX, now), Ok(Begin::New));
        registry
            .finish(&scope(), &key(u64::MAX), "alice", now)
            .unwrap();
        registry.revoke();
        registry
            .trusted_grant(&scope(), "bob", "b".into(), now)
            .unwrap();
        let mut bob = key(1);
        bob.client = "bob".into();
        assert_eq!(
            registry.begin(&scope(), &scope(), &bob, "b", &params(), now),
            Ok(Begin::New)
        );
        let mut next = scope();
        next.session = "next".into();
        registry.bind_scope(Some(next.clone()));
        registry
            .trusted_grant(&next, "alice", "token".into(), now)
            .unwrap();
        let mut next_key = key(1);
        next_key.document_session = "next".into();
        assert_eq!(
            registry.begin(&next, &next, &next_key, "token", &params(), now),
            Ok(Begin::New)
        );
    }

    #[test]
    fn failures_unchanged_and_post_commit_expiry_store_original_results() {
        let now = Instant::now();
        let mut registry = granted(now);
        for (seq, result) in [(1, "busy"), (2, "unchanged"), (3, "moved")] {
            assert_eq!(begin(&mut registry, seq, now), Ok(Begin::New));
            registry.finish(&scope(), &key(seq), result, now).unwrap();
            assert_eq!(begin(&mut registry, seq, now), Ok(Begin::Cached(result)));
        }
        assert_eq!(begin(&mut registry, 4, now), Ok(Begin::New));
        registry.revoke();
        registry
            .finish(&scope(), &key(4), "committed", now + LEASE_DURATION)
            .unwrap();
        registry
            .trusted_grant(&scope(), "alice", "token".into(), now + LEASE_DURATION)
            .unwrap();
        assert_eq!(
            begin(&mut registry, 4, now + LEASE_DURATION),
            Ok(Begin::Cached("committed"))
        );
    }
}
